# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""
BRepMeshData module, see official documentation at
https://www.opencascade.com/doc/occt-7.6.0/refman/html/package_brepmeshdata.html
"""

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _BRepMeshData
else:
    import _BRepMeshData

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _BRepMeshData.delete_SwigPyIterator

    def value(self):
        return _BRepMeshData.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _BRepMeshData.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _BRepMeshData.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _BRepMeshData.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _BRepMeshData.SwigPyIterator_equal(self, x)

    def copy(self):
        return _BRepMeshData.SwigPyIterator_copy(self)

    def next(self):
        return _BRepMeshData.SwigPyIterator_next(self)

    def __next__(self):
        return _BRepMeshData.SwigPyIterator___next__(self)

    def previous(self):
        return _BRepMeshData.SwigPyIterator_previous(self)

    def advance(self, n):
        return _BRepMeshData.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _BRepMeshData.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _BRepMeshData.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _BRepMeshData.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _BRepMeshData.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _BRepMeshData.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _BRepMeshData.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _BRepMeshData:
_BRepMeshData.SwigPyIterator_swigregister(SwigPyIterator)


def _dumps_object(klass):
    """ Overwrite default string output for any wrapped object.
    By default, __repr__ method returns something like:
    <OCC.Core.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    <class 'gp_Pnt'>
    or
    <class 'TopoDS_Shape'>
    """
    klass_name = str(klass.__class__).split(".")[3].split("'")[0]
    repr_string = "<class '" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        if klass.IsNull():
            repr_string += ": Null>"
            return repr_string
        st = klass.ShapeType()
        types = {OCC.Core.TopAbs.TopAbs_VERTEX: "Vertex",
                 OCC.Core.TopAbs.TopAbs_SOLID: "Solid",
                 OCC.Core.TopAbs.TopAbs_EDGE: "Edge",
                 OCC.Core.TopAbs.TopAbs_FACE: "Face",
                 OCC.Core.TopAbs.TopAbs_SHELL: "Shell",
                 OCC.Core.TopAbs.TopAbs_WIRE: "Wire",
                 OCC.Core.TopAbs.TopAbs_COMPOUND: "Compound",
                 OCC.Core.TopAbs.TopAbs_COMPSOLID: "Compsolid"}
        repr_string += "; Type:%s" % types[st]        
    elif hasattr(klass, "IsNull"):
        if klass.IsNull():
            repr_string += "; Null"
    repr_string += ">"
    return repr_string


def process_exception(error, method_name, class_name):
    return _BRepMeshData.process_exception(error, method_name, class_name)

from six import with_metaclass
import warnings
from OCC.Wrapper.wrapper_utils import Proxy, deprecated

import OCC.Core.Standard
import OCC.Core.NCollection
import OCC.Core.IMeshData
import OCC.Core.TopoDS
import OCC.Core.Message
import OCC.Core.TCollection
import OCC.Core.OSD
import OCC.Core.TColStd
import OCC.Core.TopAbs
import OCC.Core.TopLoc
import OCC.Core.gp
import OCC.Core.BRepAdaptor
import OCC.Core.Adaptor3d
import OCC.Core.Geom
import OCC.Core.GeomAbs
import OCC.Core.TColgp
import OCC.Core.Adaptor2d
import OCC.Core.Geom2d
import OCC.Core.math
import OCC.Core.GeomAdaptor
import OCC.Core.Geom2dAdaptor

from enum import IntEnum
from OCC.Core.Exception import *



class BRepMeshData_Curve(OCC.Core.IMeshData.IMeshData_Curve):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def AddPoint(self, *args):
        r"""
        Adds new discretization point to pcurve.

        Parameters
        ----------
        thePoint: gp_Pnt
        theParamOnCurve: float

        Returns
        -------
        None

        """
        return _BRepMeshData.BRepMeshData_Curve_AddPoint(self, *args)

    def Clear(self, *args):
        r"""
        Clears parameters list.

        Parameters
        ----------
        isKeepEndPoints: bool

        Returns
        -------
        None

        """
        return _BRepMeshData.BRepMeshData_Curve_Clear(self, *args)

    def GetParameter(self, *args):
        r"""
        Returns parameter with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        float

        """
        return _BRepMeshData.BRepMeshData_Curve_GetParameter(self, *args)

    def GetPoint(self, *args):
        r"""
        Returns discretization point with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        gp_Pnt

        """
        return _BRepMeshData.BRepMeshData_Curve_GetPoint(self, *args)

    def InsertPoint(self, *args):
        r"""
        Inserts new discretization point at the given position.

        Parameters
        ----------
        thePosition: int
        thePoint: gp_Pnt
        theParamOnPCurve: float

        Returns
        -------
        None

        """
        return _BRepMeshData.BRepMeshData_Curve_InsertPoint(self, *args)

    def ParametersNb(self, *args):
        r"""
        Returns number of parameters stored in curve.

        Returns
        -------
        int

        """
        return _BRepMeshData.BRepMeshData_Curve_ParametersNb(self, *args)

    def RemovePoint(self, *args):
        r"""
        Removes point with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        None

        """
        return _BRepMeshData.BRepMeshData_Curve_RemovePoint(self, *args)

    __repr__ = _dumps_object

    @methodnotwrapped
    def B(self):
    	pass

    @methodnotwrapped
    def R(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def p(self):
    	pass

    @methodnotwrapped
    def M(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def s(self):
    	pass

    @methodnotwrapped
    def h(self):
    	pass

    @methodnotwrapped
    def D(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def t(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def _(self):
    	pass

    @methodnotwrapped
    def C(self):
    	pass

    @methodnotwrapped
    def u(self):
    	pass

    @methodnotwrapped
    def r(self):
    	pass

    @methodnotwrapped
    def v(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    __swig_destroy__ = _BRepMeshData.delete_BRepMeshData_Curve

# Register BRepMeshData_Curve in _BRepMeshData:
_BRepMeshData.BRepMeshData_Curve_swigregister(BRepMeshData_Curve)

class BRepMeshData_Edge(OCC.Core.IMeshData.IMeshData_Edge):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def AddPCurve(self, *args):
        r"""
        Adds discrete pcurve for the specified discrete face.

        Parameters
        ----------
        theDFace: IMeshData::IFacePtr
        theOrientation: TopAbs_Orientation

        Returns
        -------
        IMeshData::IPCurveHandle

        """
        return _BRepMeshData.BRepMeshData_Edge_AddPCurve(self, *args)

    def GetPCurve(self, *args):
        r"""
        Returns pcurve for the specified discrete face.

        Parameters
        ----------
        theDFace: IMeshData::IFacePtr
        theOrientation: TopAbs_Orientation

        Returns
        -------
        IMeshData::IPCurveHandle
        Returns pcurve with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        IMeshData::IPCurveHandle

        """
        return _BRepMeshData.BRepMeshData_Edge_GetPCurve(self, *args)

    def PCurvesNb(self, *args):
        r"""
        Returns number of pcurves assigned to current edge.

        Returns
        -------
        int

        """
        return _BRepMeshData.BRepMeshData_Edge_PCurvesNb(self, *args)

    __repr__ = _dumps_object

    @methodnotwrapped
    def B(self):
    	pass

    @methodnotwrapped
    def R(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def p(self):
    	pass

    @methodnotwrapped
    def M(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def s(self):
    	pass

    @methodnotwrapped
    def h(self):
    	pass

    @methodnotwrapped
    def D(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def t(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def _(self):
    	pass

    @methodnotwrapped
    def E(self):
    	pass

    @methodnotwrapped
    def d(self):
    	pass

    @methodnotwrapped
    def g(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    __swig_destroy__ = _BRepMeshData.delete_BRepMeshData_Edge

# Register BRepMeshData_Edge in _BRepMeshData:
_BRepMeshData.BRepMeshData_Edge_swigregister(BRepMeshData_Edge)

class BRepMeshData_Face(OCC.Core.IMeshData.IMeshData_Face):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def AddWire(self, *args):
        r"""
        Adds wire to discrete model of face.

        Parameters
        ----------
        theWire: TopoDS_Wire
        theEdgeNb: int,optional
        	default value is 0

        Returns
        -------
        IMeshData::IWireHandle

        """
        return _BRepMeshData.BRepMeshData_Face_AddWire(self, *args)

    def GetWire(self, *args):
        r"""
        Gets wire with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        IMeshData::IWireHandle

        """
        return _BRepMeshData.BRepMeshData_Face_GetWire(self, *args)

    def WiresNb(self, *args):
        r"""
        Gets number of children.

        Returns
        -------
        int

        """
        return _BRepMeshData.BRepMeshData_Face_WiresNb(self, *args)

    __repr__ = _dumps_object

    @methodnotwrapped
    def B(self):
    	pass

    @methodnotwrapped
    def R(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def p(self):
    	pass

    @methodnotwrapped
    def M(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def s(self):
    	pass

    @methodnotwrapped
    def h(self):
    	pass

    @methodnotwrapped
    def D(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def t(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def _(self):
    	pass

    @methodnotwrapped
    def F(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def c(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    __swig_destroy__ = _BRepMeshData.delete_BRepMeshData_Face

# Register BRepMeshData_Face in _BRepMeshData:
_BRepMeshData.BRepMeshData_Face_swigregister(BRepMeshData_Face)

class BRepMeshData_Model(OCC.Core.IMeshData.IMeshData_Model):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Constructor. initializes empty model.

        Parameters
        ----------
        theShape: TopoDS_Shape

        Returns
        -------
        None

        """
        _BRepMeshData.BRepMeshData_Model_swiginit(self, _BRepMeshData.new_BRepMeshData_Model(*args))

    def AddEdge(self, *args):
        r"""
        Adds new edge to shape model.

        Parameters
        ----------
        theEdge: TopoDS_Edge

        Returns
        -------
        IMeshData::IEdgeHandle

        """
        return _BRepMeshData.BRepMeshData_Model_AddEdge(self, *args)

    def AddFace(self, *args):
        r"""
        Adds new face to shape model.

        Parameters
        ----------
        theFace: TopoDS_Face

        Returns
        -------
        IMeshData::IFaceHandle

        """
        return _BRepMeshData.BRepMeshData_Model_AddFace(self, *args)

    def EdgesNb(self, *args):
        r"""
        Returns number of edges in discrete model.

        Returns
        -------
        int

        """
        return _BRepMeshData.BRepMeshData_Model_EdgesNb(self, *args)

    def FacesNb(self, *args):
        r"""
        Returns number of faces in discrete model.

        Returns
        -------
        int

        """
        return _BRepMeshData.BRepMeshData_Model_FacesNb(self, *args)

    def GetEdge(self, *args):
        r"""
        Gets model's edge with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        IMeshData::IEdgeHandle

        """
        return _BRepMeshData.BRepMeshData_Model_GetEdge(self, *args)

    def GetFace(self, *args):
        r"""
        Gets model's face with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        IMeshData::IFaceHandle

        """
        return _BRepMeshData.BRepMeshData_Model_GetFace(self, *args)

    def GetMaxSize(self, *args):
        r"""
        Returns maximum size of shape's bounding box.

        Returns
        -------
        float

        """
        return _BRepMeshData.BRepMeshData_Model_GetMaxSize(self, *args)

    def SetMaxSize(self, *args):
        r"""
        Sets maximum size of shape's bounding box.

        Parameters
        ----------
        theValue: float

        Returns
        -------
        None

        """
        return _BRepMeshData.BRepMeshData_Model_SetMaxSize(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _BRepMeshData.delete_BRepMeshData_Model

# Register BRepMeshData_Model in _BRepMeshData:
_BRepMeshData.BRepMeshData_Model_swigregister(BRepMeshData_Model)

class BRepMeshData_PCurve(OCC.Core.IMeshData.IMeshData_PCurve):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def AddPoint(self, *args):
        r"""
        Adds new discretization point to pcurve.

        Parameters
        ----------
        thePoint: gp_Pnt2d
        theParamOnPCurve: float

        Returns
        -------
        None

        """
        return _BRepMeshData.BRepMeshData_PCurve_AddPoint(self, *args)

    def Clear(self, *args):
        r"""
        Clears parameters list.

        Parameters
        ----------
        isKeepEndPoints: bool

        Returns
        -------
        None

        """
        return _BRepMeshData.BRepMeshData_PCurve_Clear(self, *args)

    def GetIndex(self, *args):
        r"""
        Returns index in mesh corresponded to discretization point with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        int

        """
        return _BRepMeshData.BRepMeshData_PCurve_GetIndex(self, *args)

    def GetParameter(self, *args):
        r"""
        Returns parameter with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        float

        """
        return _BRepMeshData.BRepMeshData_PCurve_GetParameter(self, *args)

    def GetPoint(self, *args):
        r"""
        Returns discretization point with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        gp_Pnt2d

        """
        return _BRepMeshData.BRepMeshData_PCurve_GetPoint(self, *args)

    def InsertPoint(self, *args):
        r"""
        Inserts new discretization point at the given position.

        Parameters
        ----------
        thePosition: int
        thePoint: gp_Pnt2d
        theParamOnPCurve: float

        Returns
        -------
        None

        """
        return _BRepMeshData.BRepMeshData_PCurve_InsertPoint(self, *args)

    def ParametersNb(self, *args):
        r"""
        Returns number of parameters stored in pcurve.

        Returns
        -------
        int

        """
        return _BRepMeshData.BRepMeshData_PCurve_ParametersNb(self, *args)

    def RemovePoint(self, *args):
        r"""
        Removes point with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        None

        """
        return _BRepMeshData.BRepMeshData_PCurve_RemovePoint(self, *args)

    __repr__ = _dumps_object

    @methodnotwrapped
    def B(self):
    	pass

    @methodnotwrapped
    def R(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def p(self):
    	pass

    @methodnotwrapped
    def M(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def s(self):
    	pass

    @methodnotwrapped
    def h(self):
    	pass

    @methodnotwrapped
    def D(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def t(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def _(self):
    	pass

    @methodnotwrapped
    def P(self):
    	pass

    @methodnotwrapped
    def C(self):
    	pass

    @methodnotwrapped
    def u(self):
    	pass

    @methodnotwrapped
    def r(self):
    	pass

    @methodnotwrapped
    def v(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    __swig_destroy__ = _BRepMeshData.delete_BRepMeshData_PCurve

# Register BRepMeshData_PCurve in _BRepMeshData:
_BRepMeshData.BRepMeshData_PCurve_swigregister(BRepMeshData_PCurve)

class BRepMeshData_Wire(OCC.Core.IMeshData.IMeshData_Wire):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def AddEdge(self, *args):
        r"""
        Adds new discrete edge with specified orientation to wire chain. returns index of added edge in wire chain.

        Parameters
        ----------
        theDEdge: IMeshData::IEdgePtr
        theOrientation: TopAbs_Orientation

        Returns
        -------
        int

        """
        return _BRepMeshData.BRepMeshData_Wire_AddEdge(self, *args)

    def EdgesNb(self, *args):
        r"""
        Gets number of children.

        Returns
        -------
        int

        """
        return _BRepMeshData.BRepMeshData_Wire_EdgesNb(self, *args)

    def GetEdge(self, *args):
        r"""
        Gets edge with the given index.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        IMeshData::IEdgePtr

        """
        return _BRepMeshData.BRepMeshData_Wire_GetEdge(self, *args)

    def GetEdgeOrientation(self, *args):
        r"""
        Returns true if orientation of discrete edge with the given index is forward.

        Parameters
        ----------
        theIndex: int

        Returns
        -------
        TopAbs_Orientation

        """
        return _BRepMeshData.BRepMeshData_Wire_GetEdgeOrientation(self, *args)

    __repr__ = _dumps_object

    @methodnotwrapped
    def B(self):
    	pass

    @methodnotwrapped
    def R(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def p(self):
    	pass

    @methodnotwrapped
    def M(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    @methodnotwrapped
    def s(self):
    	pass

    @methodnotwrapped
    def h(self):
    	pass

    @methodnotwrapped
    def D(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def t(self):
    	pass

    @methodnotwrapped
    def a(self):
    	pass

    @methodnotwrapped
    def _(self):
    	pass

    @methodnotwrapped
    def W(self):
    	pass

    @methodnotwrapped
    def i(self):
    	pass

    @methodnotwrapped
    def r(self):
    	pass

    @methodnotwrapped
    def e(self):
    	pass

    __swig_destroy__ = _BRepMeshData.delete_BRepMeshData_Wire

# Register BRepMeshData_Wire in _BRepMeshData:
_BRepMeshData.BRepMeshData_Wire_swigregister(BRepMeshData_Wire)





